### ISSUE TITLE
Make the nav bar transition smooth and intuitive

### ISSUE THREAD

**Issue by g4ze** [GDG-OnCampus-BU/landing-page-WIP#3]
Atm, when clicking `Discover More` on the landing page, the navbar appears very suddenly. We want the navbar to appear on scroll as well as on click in a smooth fasion.
1 - When we land on the page, the navbar shouldn't be visible
2 - If we scroll as soon as we land on the page, the navbar shouldn't be visible 
3 - If we scroll up at any point of time, the navbar should become visible
4 - If we scroll down again, the navbar should hide

Just propose a solution with whatever understanding you can make out of this and the we can further discuss upon it :)

**Comment by genial-mani** [comment]
I already worked on my project like this you can check here https://fullstack-marketing-hub.vercel.app/
If you assign me I will start working on this.

**Comment by g4ze** [comment]
Sure go ahead!
